# Generated by Django 3.2 on 2022-05-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_auto_20220524_1520'),
        ('dogs', '0003_auto_20220522_2355'),
    ]

    operations = [
    ]
