# Generated by Django 3.2 on 2022-05-31 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_auto_20220511_1016'),
        ('dogs', '0004_merge_0002_auto_20220524_1520_0003_auto_20220522_2355'),
    ]

    operations = [
    ]
