# Generated by Django 3.2 on 2022-05-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_merge_20220531_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.TextField(),
        ),
    ]
