# Generated by Django 3.2 on 2022-05-31 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_auto_20220530_2203'),
        ('dogs', '0006_alter_dog_image'),
    ]

    operations = [
    ]
