# Generated by Django 3.2 on 2022-05-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userdog', models.CharField(max_length=10)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('press_time', models.IntegerField(blank=True, null=True)),
                ('elapsed_time', models.IntegerField(blank=True, null=True)),
                ('evaluate', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'timestamp_auth',
            },
        ),
    ]
