# Generated by Django 3.2 on 2022-05-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='press_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
