# Generated by Django 3.2 on 2022-05-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp', '0003_auto_20220529_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='press_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
