version: "3"

services:
        web:
                build:
                  context: .
                  dockerfile: ./localbind.Dockerfile
                command: >
                       bash -c ""
                ports:
                        - 8000:8000
                volumes:
                        - ./:/var/jenkins_home/workspace/Pupple/backend/pupple_backend/
                restart: always
