# Generated by Django 3.2 on 2022-05-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatDetector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(blank=True, null=True)),
                ('dog_id', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('result', models.TextField(default='inProgress')),
            ],
            options={
                'db_table': 'mat_detector',
            },
        ),
    ]
