# Generated by Django 3.2 on 2022-05-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='food_cost',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='vaccin_cost',
            field=models.TextField(),
        ),
    ]
