# Generated by Django 3.2 on 2022-05-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassCondition',
            fields=[
                ('dog_id', models.IntegerField(primary_key=True, serialize=False)),
                ('walk_total_count', models.IntegerField(blank=True, null=True)),
                ('min_per_walk', models.IntegerField(blank=True, null=True)),
                ('meter_per_walk', models.IntegerField(blank=True, null=True)),
                ('ts_total_count', models.IntegerField(blank=True, null=True)),
                ('ts_check_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pass_condition',
            },
        ),
    ]
