# Generated by Django 3.2 on 2022-05-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user_type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
