# Generated by Django 3.2 on 2022-05-07 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField()),
                ('ispass', models.BooleanField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housephoto', to='dogs.dog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housephoto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
