# Generated by Django 3.2 on 2022-05-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_photo', '0002_alter_housephoto_ispass'),
        ('house_photo', '0002_auto_20220522_2355'),
    ]

    operations = [
    ]
