# Generated by Django 3.2 on 2022-04-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkauth',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
