# Generated by Django 3.2 on 2022-04-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walkauth', '0002_walkauth_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkauth',
            name='index',
        ),
    ]
